baseurl: http://icyleaf.com/
languageCode: en-us
title: icyleaf
theme: casper
paginate: 10
disqusShortname: icyleaf
hasCJKLanguage: true
MetaDataFormat: yaml
canonifyURLs: true
copyright: All rights reserved - 2007
params:
  description: 热爱户外的码农、下厨初心者
  author: icyleaf
  cover: images/cover.jpg
  index: true
  RSSLink: feed.xml
  # footer in post
  authorlocation: Beijing, China
  authorwebsite: http://icyleaf.com
  bio: 热爱户外的码农、下厨初心者
  # Global theme settings
  logo: images/icyleaf-icon.png
  googleAnalyticsUserID: UA-2570916-5
  socials:
    - name: github
      link: https://github.com/icyleaf
    - name: twitter
      link: https://twitter.com/icyleaf
    - name: facebook
      link: https://www.facebook.com/icyleaf
    - name: linkedin
      link: https://www.linkedin.com/in/icyleaf
    - name: instagram
      link: https://www.instagram.com/icyleaf/
    - name: weibo
      link: http://weibo.com/icy1eaf
    - name: douban
      link: https://www.douban.com/people/icyleaf

  hideHUGOSupport: false
  share: true

permalinks:
  post: /:year/:month/:slug
  page: /:filename

taxonomies:
  tag: tags
  category: categories

menu:
  main:
    - name: Home
      weight: -120
      identifier: blog
      url: /
    - name: Technology
      weight: -110
      identifier: technology
      url: /categories/technology
    - name: Tags
      weight: -100
      identifier: tags
      url: /tags
    - name: About
      weight: -90
      identifier: about
      url: /about
